env:
  global:
    - secure: "lZ7pHQvl5dpZWzBQAaIMf0wqrvtcZ4wiZKeIZjf83TEsflW8+z0uTpIuN30ZV6Glth/Sq1OhLnTP5+N57fZU/1ebA5twHdvP4bS5CIUUg71/CXQZNl36xeaqvxsG/xRrdpKOsPdjAOsQ9KPTQulsX43XDLS7CasMiLvYOpqKcPc="

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

language: cpp

compiler:
  - gcc
  - clang

before_script:
  cmake .

script:
  make

addons:
  coverity_scan:
    project:
      name: "assimp/assimp"
    notification_email: kim.kulling@googlemail.com
    build_command_prepend: "cmake ."
    build_command: "make -j4"
    branch_pattern: coverity_scan
