before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cmake python3
  - if [ $LINUX ]; then sudo apt-get install -qq freeglut3-dev libxmu-dev libxi-dev ; fi
  - echo -e "#ifndef A_R_H_INC\n#define A_R_H_INC\n#define GitVersion ${TRAVIS_JOB_ID}\n#define GitBranch \"${TRAVIS_BRANCH}\"\n#endif // A_R_H_INC" > revision.h

branches:
  only:
    - master

env:
  global:
    - PV=r8e PLATF=linux-x86_64 NDK_HOME=${TRAVIS_BUILD_DIR}/android-ndk-${PV} PATH=${PATH}:${NDK_HOME}
    - secure: "lZ7pHQvl5dpZWzBQAaIMf0wqrvtcZ4wiZKeIZjf83TEsflW8+z0uTpIuN30ZV6Glth/Sq1OhLnTP5+N57fZU/1ebA5twHdvP4bS5CIUUg71/CXQZNl36xeaqvxsG/xRrdpKOsPdjAOsQ9KPTQulsX43XDLS7CasMiLvYOpqKcPc="
  matrix:
    - LINUX=1 TRAVIS_NO_EXPORT=YES
    - LINUX=1 TRAVIS_NO_EXPORT=NO
    - LINUX=1 SHARED_BUILD=ON
    - LINUX=1 SHARED_BUILD=OFF
    - ANDROID=1

language: cpp

compiler:
  - gcc
  - clang

install:
  - if [ $ANDROID ]; then wget -c http://dl.google.com/android/ndk/android-ndk-${PV}-${PLATF}.tar.bz2 && tar xf android-ndk-${PV}-${PLATF}.tar.bz2 ; fi

script:
  - . ./.travis.sh

addons:
  coverity_scan:
    project:
      name: "assimp/assimp"
      description: "<Your project description here>"
      notification_email: kim.kulling@googlemail.com
	build_command_prepend: cmake -G "Unix Makefiles" -DASSIMP_ENABLE_BOOST_WORKAROUND=YES -DASSIMP_NO_EXPORT=$TRAVIS_NO_EXPORT -DBUILD_SHARED_LIBS=$SHARED_BUILD
    build_command:   make< make install
    branch_pattern: coverity_scan
