# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\assimp

shallow_clone: true

# branches to build
branches:
  # whitelist
  only:
    - master

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
    
platform:
  - x86
  - x64

configuration: Release

build:
  parallel: true
  project: Assimp.sln

install:
  - @echo off
  - set CMAKE_DEFINES -DASSIMP_WERROR=ON
  - if "%platform%"=="x86" set CMAKE_GENERATOR_NAME=%APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=%APPVEYOR_BUILD_WORKER_IMAGE% Win64
  - cmake %CMAKE_DEFINES% -G "%CMAKE_GENERATOR_NAME%"

cache:
  - code\assimp.dir\%CONFIGURATION%
  
after_build:
  - 7z a assimp.7z %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\* %APPVEYOR_BUILD_FOLDER%\lib\%CONFIGURATION%\*
  
before_test:
  - xcopy /s "%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\" "%APPVEYOR_BUILD_FOLDER%\test\%CONFIGURATION%\"

test:
  assemblies:
    only:
      - test\%CONFIGURATION%\unit.exe
  
artifacts:
  - path: assimp.7z
    name: assimp_lib
