# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# clone directory
clone_folder: c:\projects\assimp

# branches to build
branches:
  # whitelist
  only:
    - master

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017
    
platform:
  - Win32
  - x64

configuration: Release

build:
  parallel: true
  project: Assimp.sln

install:
  - set CMAKE_DEFINES -DASSIMP_WERROR=ON
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" set CMAKE_GENERATOR_NAME=Visual Studio 12 2013
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_NAME% Win64
  - cmake %CMAKE_DEFINES% -G "%CMAKE_GENERATOR_NAME%"

cache:
  - assimp.dir\%CONFIGURATION%
  
after_build:
  - 7z a assimp.7z %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\* %APPVEYOR_BUILD_FOLDER%\lib\%CONFIGURATION%\*

test_script:
  - cmd: bin\%CONFIGURATION%\unit.exe
  
artifacts:
  - path: assimp.7z
    name: assimp_lib
